### PR TITLE
Re-implement simple dependencies internally

### LINKED ISSUE #7: Deprecation warnings caused by node-byline dependency
@rmg @sam-github On node 10 I'm having deprecation warnings using `strong-log-transformer` due to it's `node-byline` dependency usage of the node `Buffer` api. I've already opened a PR against `node-byline` (https://github.com/jahewson/node-byline/pull/53) in order to fix those problems, but the library seems to be very unmaintained so far, so I don't think if the PR will ever get merged and released. 

In case that happens it might be a good idea try to replace this `node-byline` with other with the same needed features.

### PR DESCRIPTION
**Pull request by rmg**
While re-implementing the line splitting functionality of byline to resolve #7, it became obvious that the other convenience dependencies weren't really pulling their weight.

### CODE REVIEW

**Comment by rmg** [comment]
CI failures on node v4 are related to tapjs/node-tap#479. Still trying to decide how to address that.

**Comment by sam-github** [comment]
We could fork byline :-(. I brought this up in https://github.com/nodejs/package-maintenance/issues/4#issuecomment-447074748, FYI

**Review by sam-github — APPROVED** [review]

**Comment by rmg** [comment]
> it took 86 new lines for that change alone here (and yes, I count test code, we didn't need the test code when using byline, which already had tests).

In this case I don't count the test lines. We happened to inherit the behaviour from byline, but if byline's behaviour changed we wouldn't know it without those tests. I'm back-porting them in #9 because this PR has turned in to a major rewrite/refactor and as such shouldn't be modifying _any_ tests.

**Comment by rmg** [comment]
The replacement of `byline` was simplified slightly, landed as 430807f, and released it as v2.1.0.

I'm closing this PR now while I work on other things. The changes will probably come back in the form of a semver-major release that also drops the CLI which will allow _all_ dependencies to be removed.

**Pull request closed without merging**
